apiVersion: v1
kind: Template
metadata:
  name: kebechet-secret
  annotations:
    description: This is Kebechet Secret, this template is meant to be used by Bots, but could also be used by humans...
    openshift.io/display-name: Kebechet Secret
    version: 1.0.1
    tags: thoth,ai-stacks,kebechet,cyborg,srcops
    template.openshift.io/documentation-url: https://github.com/thoth-station/kebechet/
    template.openshift.io/long-description: This is Kebechet used for automatic package releases and updates.
    template.openshift.io/provider-display-name: Red Hat, Inc.
    thoth-station.ninja/template-version: 1.0.1
  labels:
    template: kebechet-secret
    app: kebechet

objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: kebechet-secret
      labels:
        app: kebechet
      annotations:
        thoth-station.ninja/template-version: 1.0.1
    stringData:
      ssh-privatekey: ${KEBECHET_SSH_PRIVATE_KEY}
      github-oauth-token: ${GITHUB_KEBECHET_TOKEN}
      gitlab-oauth-token: ${GITLAB_KEBECHET_TOKEN}
      pagure-oauth-token: ${PAGURE_KEBECHET_TOKEN}

parameters:
  - description: SSH private key to authenticate the public key set in GitHub.
    displayName: SSH Private Key
    required: true
    name: KEBECHET_SSH_PRIVATE_KEY

  - description: GitHub OAuth token used for authentication.
    displayName: GitHub Oauth token
    required: true
    name: GITHUB_KEBECHET_TOKEN

  - description: GitLab OAuth token used for authentication
    displayName: GitLab OAuth token
    required: true
    name: GITLAB_KEBECHET_TOKEN

  - description: PAGURE_KEBECHET_TOKEN
    displayName: Pagure OAuth token
    required: true
    name: PAGURE_KEBECHET_TOKEN
